// <auto-generated />
using System;
using CibusMed_App.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CibusMed_App.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20251030101002_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CibusMed_App.Domains.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.smith@email.com",
                            Name = "John Smith"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sarah.johnson@email.com",
                            Name = "Sarah Johnson"
                        },
                        new
                        {
                            Id = 3,
                            Email = "michael.brown@email.com",
                            Name = "Michael Brown"
                        },
                        new
                        {
                            Id = 4,
                            Email = "emily.davis@email.com",
                            Name = "Emily Davis"
                        },
                        new
                        {
                            Id = 5,
                            Email = "david.wilson@email.com",
                            Name = "David Wilson"
                        },
                        new
                        {
                            Id = 6,
                            Email = "lisa.anderson@email.com",
                            Name = "Lisa Anderson"
                        },
                        new
                        {
                            Id = 7,
                            Email = "james.taylor@email.com",
                            Name = "James Taylor"
                        },
                        new
                        {
                            Id = 8,
                            Email = "maria.garcia@email.com",
                            Name = "Maria Garcia"
                        },
                        new
                        {
                            Id = 9,
                            Email = "robert.martinez@email.com",
                            Name = "Robert Martinez"
                        },
                        new
                        {
                            Id = 10,
                            Email = "jennifer.lee@email.com",
                            Name = "Jennifer Lee"
                        });
                });

            modelBuilder.Entity("CibusMed_App.Domains.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2025, 8, 31, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(2989),
                            CustomerId = 1,
                            Notes = "Test order in Pending status",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2025, 10, 17, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3156),
                            CustomerId = 2,
                            Notes = "Test order in Approved status",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2025, 10, 18, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3162),
                            CustomerId = 3,
                            Notes = "Test order in Shipped status",
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2025, 9, 13, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3166),
                            CustomerId = 4,
                            Notes = "Test order in Cancelled status",
                            Status = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2025, 10, 15, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3195),
                            CustomerId = 5,
                            Notes = "Order for customer 5",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAtUtc = new DateTime(2025, 8, 26, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3215),
                            CustomerId = 6,
                            Notes = "Order for customer 6",
                            Status = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAtUtc = new DateTime(2025, 10, 14, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3221),
                            CustomerId = 7,
                            Notes = "Order for customer 7",
                            Status = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedAtUtc = new DateTime(2025, 10, 9, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3226),
                            CustomerId = 8,
                            Notes = "Order for customer 8",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAtUtc = new DateTime(2025, 9, 15, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3232),
                            CustomerId = 9,
                            Notes = "Order for customer 9",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAtUtc = new DateTime(2025, 9, 26, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3239),
                            CustomerId = 10,
                            Notes = "Order for customer 10",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAtUtc = new DateTime(2025, 10, 26, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3248),
                            CustomerId = 6,
                            Status = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAtUtc = new DateTime(2025, 10, 16, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3251),
                            CustomerId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAtUtc = new DateTime(2025, 9, 11, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3252),
                            CustomerId = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAtUtc = new DateTime(2025, 8, 10, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3254),
                            CustomerId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAtUtc = new DateTime(2025, 10, 26, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3255),
                            CustomerId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAtUtc = new DateTime(2025, 10, 29, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3257),
                            CustomerId = 9,
                            Status = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAtUtc = new DateTime(2025, 9, 25, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3258),
                            CustomerId = 8,
                            Notes = "Order #17",
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatedAtUtc = new DateTime(2025, 8, 21, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3264),
                            CustomerId = 1,
                            Notes = "Order #18",
                            Status = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAtUtc = new DateTime(2025, 8, 22, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3267),
                            CustomerId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAtUtc = new DateTime(2025, 10, 26, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3269),
                            CustomerId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 21,
                            CreatedAtUtc = new DateTime(2025, 9, 22, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3270),
                            CustomerId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 22,
                            CreatedAtUtc = new DateTime(2025, 10, 28, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3272),
                            CustomerId = 3,
                            Notes = "Order #22",
                            Status = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAtUtc = new DateTime(2025, 8, 27, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3275),
                            CustomerId = 1,
                            Notes = "Order #23",
                            Status = 0
                        },
                        new
                        {
                            Id = 24,
                            CreatedAtUtc = new DateTime(2025, 8, 19, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3277),
                            CustomerId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAtUtc = new DateTime(2025, 10, 29, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3279),
                            CustomerId = 5,
                            Notes = "Order #25",
                            Status = 3
                        },
                        new
                        {
                            Id = 26,
                            CreatedAtUtc = new DateTime(2025, 10, 24, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3282),
                            CustomerId = 1,
                            Notes = "Order #26",
                            Status = 2
                        },
                        new
                        {
                            Id = 27,
                            CreatedAtUtc = new DateTime(2025, 8, 8, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3285),
                            CustomerId = 10,
                            Notes = "Order #27",
                            Status = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAtUtc = new DateTime(2025, 10, 26, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3287),
                            CustomerId = 7,
                            Notes = "Order #28",
                            Status = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedAtUtc = new DateTime(2025, 8, 20, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3290),
                            CustomerId = 5,
                            Notes = "Order #29",
                            Status = 2
                        },
                        new
                        {
                            Id = 30,
                            CreatedAtUtc = new DateTime(2025, 8, 10, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3293),
                            CustomerId = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 31,
                            CreatedAtUtc = new DateTime(2025, 8, 12, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3294),
                            CustomerId = 1,
                            Notes = "Order #31",
                            Status = 3
                        },
                        new
                        {
                            Id = 32,
                            CreatedAtUtc = new DateTime(2025, 10, 15, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3297),
                            CustomerId = 8,
                            Notes = "Order #32",
                            Status = 0
                        },
                        new
                        {
                            Id = 33,
                            CreatedAtUtc = new DateTime(2025, 8, 21, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3300),
                            CustomerId = 4,
                            Notes = "Order #33",
                            Status = 0
                        },
                        new
                        {
                            Id = 34,
                            CreatedAtUtc = new DateTime(2025, 9, 7, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3303),
                            CustomerId = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 35,
                            CreatedAtUtc = new DateTime(2025, 8, 31, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3305),
                            CustomerId = 8,
                            Notes = "Order #35",
                            Status = 2
                        },
                        new
                        {
                            Id = 36,
                            CreatedAtUtc = new DateTime(2025, 8, 2, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3308),
                            CustomerId = 6,
                            Notes = "Order #36",
                            Status = 2
                        },
                        new
                        {
                            Id = 37,
                            CreatedAtUtc = new DateTime(2025, 8, 8, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3311),
                            CustomerId = 4,
                            Notes = "Order #37",
                            Status = 0
                        },
                        new
                        {
                            Id = 38,
                            CreatedAtUtc = new DateTime(2025, 10, 26, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3313),
                            CustomerId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 39,
                            CreatedAtUtc = new DateTime(2025, 10, 21, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3315),
                            CustomerId = 5,
                            Notes = "Order #39",
                            Status = 3
                        },
                        new
                        {
                            Id = 40,
                            CreatedAtUtc = new DateTime(2025, 10, 1, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3318),
                            CustomerId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 41,
                            CreatedAtUtc = new DateTime(2025, 10, 29, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3319),
                            CustomerId = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = 42,
                            CreatedAtUtc = new DateTime(2025, 10, 8, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3321),
                            CustomerId = 9,
                            Status = 3
                        },
                        new
                        {
                            Id = 43,
                            CreatedAtUtc = new DateTime(2025, 9, 11, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3323),
                            CustomerId = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 44,
                            CreatedAtUtc = new DateTime(2025, 10, 3, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3364),
                            CustomerId = 2,
                            Notes = "Order #44",
                            Status = 0
                        },
                        new
                        {
                            Id = 45,
                            CreatedAtUtc = new DateTime(2025, 8, 7, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3368),
                            CustomerId = 3,
                            Status = 3
                        },
                        new
                        {
                            Id = 46,
                            CreatedAtUtc = new DateTime(2025, 8, 12, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3369),
                            CustomerId = 2,
                            Notes = "Order #46",
                            Status = 0
                        },
                        new
                        {
                            Id = 47,
                            CreatedAtUtc = new DateTime(2025, 9, 10, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3372),
                            CustomerId = 6,
                            Notes = "Order #47",
                            Status = 2
                        },
                        new
                        {
                            Id = 48,
                            CreatedAtUtc = new DateTime(2025, 9, 25, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3375),
                            CustomerId = 6,
                            Notes = "Order #48",
                            Status = 3
                        },
                        new
                        {
                            Id = 49,
                            CreatedAtUtc = new DateTime(2025, 8, 5, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3378),
                            CustomerId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 50,
                            CreatedAtUtc = new DateTime(2025, 8, 18, 10, 10, 1, 435, DateTimeKind.Utc).AddTicks(3379),
                            CustomerId = 10,
                            Notes = "Order #50",
                            Status = 0
                        });
                });

            modelBuilder.Entity("CibusMed_App.Domains.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 5,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 3,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 5,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 10,
                            Quantity = 5,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 4,
                            Quantity = 3,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 4,
                            ProductId = 10,
                            Quantity = 5,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            ProductId = 4,
                            Quantity = 3,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 5,
                            ProductId = 3,
                            Quantity = 5,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 5,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 5,
                            ProductId = 9,
                            Quantity = 4,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 5,
                            ProductId = 1,
                            Quantity = 3,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 13,
                            OrderId = 6,
                            ProductId = 9,
                            Quantity = 4,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 14,
                            OrderId = 6,
                            ProductId = 10,
                            Quantity = 5,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 15,
                            OrderId = 6,
                            ProductId = 5,
                            Quantity = 5,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 16,
                            OrderId = 6,
                            ProductId = 2,
                            Quantity = 3,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 17,
                            OrderId = 7,
                            ProductId = 7,
                            Quantity = 3,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 18,
                            OrderId = 8,
                            ProductId = 2,
                            Quantity = 5,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 19,
                            OrderId = 8,
                            ProductId = 4,
                            Quantity = 3,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 20,
                            OrderId = 8,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 21,
                            OrderId = 9,
                            ProductId = 8,
                            Quantity = 3,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 22,
                            OrderId = 9,
                            ProductId = 2,
                            Quantity = 5,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 23,
                            OrderId = 9,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 24,
                            OrderId = 10,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 25,
                            OrderId = 11,
                            ProductId = 3,
                            Quantity = 5,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 26,
                            OrderId = 11,
                            ProductId = 5,
                            Quantity = 2,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 27,
                            OrderId = 12,
                            ProductId = 8,
                            Quantity = 4,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 28,
                            OrderId = 12,
                            ProductId = 10,
                            Quantity = 2,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 29,
                            OrderId = 13,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 30,
                            OrderId = 13,
                            ProductId = 10,
                            Quantity = 3,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 31,
                            OrderId = 13,
                            ProductId = 7,
                            Quantity = 2,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 32,
                            OrderId = 13,
                            ProductId = 1,
                            Quantity = 3,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 33,
                            OrderId = 14,
                            ProductId = 4,
                            Quantity = 5,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 34,
                            OrderId = 14,
                            ProductId = 9,
                            Quantity = 5,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 35,
                            OrderId = 14,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 36,
                            OrderId = 14,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 79.99m
                        },
                        new
                        {
                            Id = 37,
                            OrderId = 15,
                            ProductId = 5,
                            Quantity = 4,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 38,
                            OrderId = 15,
                            ProductId = 7,
                            Quantity = 5,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 39,
                            OrderId = 15,
                            ProductId = 3,
                            Quantity = 5,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 40,
                            OrderId = 15,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 41,
                            OrderId = 16,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 42,
                            OrderId = 16,
                            ProductId = 6,
                            Quantity = 2,
                            UnitPrice = 79.99m
                        },
                        new
                        {
                            Id = 43,
                            OrderId = 17,
                            ProductId = 3,
                            Quantity = 4,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 44,
                            OrderId = 17,
                            ProductId = 7,
                            Quantity = 4,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 45,
                            OrderId = 18,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 46,
                            OrderId = 18,
                            ProductId = 2,
                            Quantity = 5,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 47,
                            OrderId = 19,
                            ProductId = 10,
                            Quantity = 2,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 48,
                            OrderId = 19,
                            ProductId = 1,
                            Quantity = 3,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 49,
                            OrderId = 20,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 50,
                            OrderId = 20,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 51,
                            OrderId = 21,
                            ProductId = 2,
                            Quantity = 4,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 52,
                            OrderId = 21,
                            ProductId = 7,
                            Quantity = 4,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 53,
                            OrderId = 21,
                            ProductId = 9,
                            Quantity = 2,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 54,
                            OrderId = 21,
                            ProductId = 5,
                            Quantity = 3,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 55,
                            OrderId = 22,
                            ProductId = 8,
                            Quantity = 3,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 56,
                            OrderId = 23,
                            ProductId = 7,
                            Quantity = 3,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 57,
                            OrderId = 23,
                            ProductId = 10,
                            Quantity = 4,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 58,
                            OrderId = 23,
                            ProductId = 3,
                            Quantity = 2,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 59,
                            OrderId = 24,
                            ProductId = 9,
                            Quantity = 4,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 60,
                            OrderId = 24,
                            ProductId = 4,
                            Quantity = 3,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 61,
                            OrderId = 24,
                            ProductId = 8,
                            Quantity = 3,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 62,
                            OrderId = 25,
                            ProductId = 6,
                            Quantity = 5,
                            UnitPrice = 79.99m
                        },
                        new
                        {
                            Id = 63,
                            OrderId = 25,
                            ProductId = 1,
                            Quantity = 3,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 64,
                            OrderId = 25,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 65,
                            OrderId = 25,
                            ProductId = 10,
                            Quantity = 3,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 66,
                            OrderId = 26,
                            ProductId = 5,
                            Quantity = 4,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 67,
                            OrderId = 26,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 68,
                            OrderId = 27,
                            ProductId = 5,
                            Quantity = 5,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 69,
                            OrderId = 27,
                            ProductId = 10,
                            Quantity = 3,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 70,
                            OrderId = 27,
                            ProductId = 3,
                            Quantity = 5,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 71,
                            OrderId = 27,
                            ProductId = 9,
                            Quantity = 4,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 72,
                            OrderId = 28,
                            ProductId = 9,
                            Quantity = 3,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 73,
                            OrderId = 28,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 74,
                            OrderId = 28,
                            ProductId = 2,
                            Quantity = 5,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 75,
                            OrderId = 29,
                            ProductId = 10,
                            Quantity = 3,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 76,
                            OrderId = 29,
                            ProductId = 2,
                            Quantity = 2,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 77,
                            OrderId = 29,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 78,
                            OrderId = 30,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 79,
                            OrderId = 31,
                            ProductId = 10,
                            Quantity = 5,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 80,
                            OrderId = 32,
                            ProductId = 4,
                            Quantity = 3,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 81,
                            OrderId = 32,
                            ProductId = 2,
                            Quantity = 4,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 82,
                            OrderId = 32,
                            ProductId = 3,
                            Quantity = 3,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 83,
                            OrderId = 32,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 84,
                            OrderId = 33,
                            ProductId = 1,
                            Quantity = 3,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 85,
                            OrderId = 33,
                            ProductId = 8,
                            Quantity = 3,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 86,
                            OrderId = 33,
                            ProductId = 10,
                            Quantity = 4,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 87,
                            OrderId = 34,
                            ProductId = 4,
                            Quantity = 3,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 88,
                            OrderId = 34,
                            ProductId = 9,
                            Quantity = 4,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 89,
                            OrderId = 34,
                            ProductId = 10,
                            Quantity = 5,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 90,
                            OrderId = 34,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 91,
                            OrderId = 35,
                            ProductId = 10,
                            Quantity = 5,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 92,
                            OrderId = 35,
                            ProductId = 2,
                            Quantity = 4,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 93,
                            OrderId = 35,
                            ProductId = 9,
                            Quantity = 5,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 94,
                            OrderId = 35,
                            ProductId = 5,
                            Quantity = 5,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 95,
                            OrderId = 36,
                            ProductId = 3,
                            Quantity = 5,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 96,
                            OrderId = 37,
                            ProductId = 6,
                            Quantity = 5,
                            UnitPrice = 79.99m
                        },
                        new
                        {
                            Id = 97,
                            OrderId = 37,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 98,
                            OrderId = 38,
                            ProductId = 4,
                            Quantity = 5,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 99,
                            OrderId = 38,
                            ProductId = 2,
                            Quantity = 5,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 100,
                            OrderId = 38,
                            ProductId = 9,
                            Quantity = 3,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 101,
                            OrderId = 38,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 102,
                            OrderId = 39,
                            ProductId = 7,
                            Quantity = 2,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 103,
                            OrderId = 39,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 104,
                            OrderId = 39,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 105,
                            OrderId = 40,
                            ProductId = 5,
                            Quantity = 2,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 106,
                            OrderId = 41,
                            ProductId = 10,
                            Quantity = 4,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 107,
                            OrderId = 41,
                            ProductId = 3,
                            Quantity = 5,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 108,
                            OrderId = 41,
                            ProductId = 5,
                            Quantity = 4,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 109,
                            OrderId = 42,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 110,
                            OrderId = 42,
                            ProductId = 9,
                            Quantity = 5,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 111,
                            OrderId = 42,
                            ProductId = 10,
                            Quantity = 2,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 112,
                            OrderId = 43,
                            ProductId = 5,
                            Quantity = 5,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 113,
                            OrderId = 44,
                            ProductId = 1,
                            Quantity = 5,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 114,
                            OrderId = 44,
                            ProductId = 5,
                            Quantity = 5,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 115,
                            OrderId = 44,
                            ProductId = 8,
                            Quantity = 5,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 116,
                            OrderId = 44,
                            ProductId = 3,
                            Quantity = 5,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 117,
                            OrderId = 45,
                            ProductId = 7,
                            Quantity = 4,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 118,
                            OrderId = 46,
                            ProductId = 8,
                            Quantity = 3,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 119,
                            OrderId = 46,
                            ProductId = 7,
                            Quantity = 2,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 120,
                            OrderId = 47,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 121,
                            OrderId = 47,
                            ProductId = 5,
                            Quantity = 3,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 122,
                            OrderId = 48,
                            ProductId = 5,
                            Quantity = 4,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 123,
                            OrderId = 48,
                            ProductId = 2,
                            Quantity = 4,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 124,
                            OrderId = 49,
                            ProductId = 4,
                            Quantity = 5,
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 125,
                            OrderId = 49,
                            ProductId = 10,
                            Quantity = 2,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 126,
                            OrderId = 49,
                            ProductId = 3,
                            Quantity = 2,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 127,
                            OrderId = 49,
                            ProductId = 5,
                            Quantity = 3,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 128,
                            OrderId = 50,
                            ProductId = 2,
                            Quantity = 5,
                            UnitPrice = 89.99m
                        });
                });

            modelBuilder.Entity("CibusMed_App.Domains.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wireless Mouse",
                            Sku = "PRD-001",
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mechanical Keyboard",
                            Sku = "PRD-002",
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 3,
                            Name = "USB-C Cable",
                            Sku = "PRD-003",
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Monitor Stand",
                            Sku = "PRD-004",
                            UnitPrice = 45.99m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Webcam HD",
                            Sku = "PRD-005",
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Headset",
                            Sku = "PRD-006",
                            UnitPrice = 79.99m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Laptop Sleeve",
                            Sku = "PRD-007",
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Desk Lamp",
                            Sku = "PRD-008",
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 9,
                            Name = "External SSD 1TB",
                            Sku = "PRD-009",
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ergonomic Chair Cushion",
                            Sku = "PRD-010",
                            UnitPrice = 39.99m
                        });
                });

            modelBuilder.Entity("CibusMed_App.Domains.Order", b =>
                {
                    b.HasOne("CibusMed_App.Domains.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CibusMed_App.Domains.OrderItem", b =>
                {
                    b.HasOne("CibusMed_App.Domains.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CibusMed_App.Domains.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CibusMed_App.Domains.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CibusMed_App.Domains.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CibusMed_App.Domains.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
